### ISSUE TITLE
What I wish I knew before I started programming

### ISSUE THREAD

**Issue by Lumary2** [Lumary2/Developer-resources-and-tips#2]
In the folder "What I wish I knew before I started programming" add your tips concerning that topic and if you want add your Github name as well.

**Comment by kaeptnkrunch** [comment]
I finished this "Issue". I also linked my **GitHub**.

**Comment by Lumary2** [comment]
Thanks for adding to it! I leave it open because it's suppose to collect experiences from anyone. 😊
